using System;
using System.Collections.Generic;
using System.Text;

namespace Excel_SQLizer
{
    public abstract class BaseStatementGenerator : IStatementGenerator
    {

        /// <summary>
        /// The statements generated by the StatementGenerator
        /// </summary>
        protected List<string> _statements;
        /// <summary>
        /// The statement prefix - the beginning of each statement
        /// E.g. INSERT INTO EXAMPLE_TABLE (Field1, Field2, Field3) 
        /// </summary>
        protected string _statementPrefix;
        /// <summary>
        /// The where clause
        /// </summary>
        protected string _whereClause;
        /// <summary>
        /// The file name of the generated statements.
        /// </summary>
        protected string _fileName;

        /// <summary>
        /// Initializes generator properties.
        /// </summary>
        /// <param name="statementPrefix">The statement prefix.</param>
        /// <param name="whereClause">The where clause.</param>
        protected void Initialize(string statementPrefix, string fileName, string whereClause = null)
        {
            _statementPrefix = statementPrefix;
            _whereClause     = whereClause;
            _fileName        = fileName;
        }

        /// <summary>
        /// Adds the statement to the list of generated statements.
        /// </summary>
        /// <param name="values">The values to add. Comma delimited.</param>
        public abstract void AddStatement(string values);

        /// <summary>
        /// Gets the statements.
        /// </summary>
        /// <returns>
        /// A list of all generated statements
        /// </returns>
        public List<string> GetStatements()
        {
            return _statements;
        }

        /// <summary>
        /// Gets the name of the file.
        /// </summary>
        /// <returns></returns>
        public string GetFileName()
        {
            return _fileName;
        }
    }
}
